[package]
name = "ntex-grpc"
version = "3.0.0-beta.0"
license = "MIT OR Apache-2.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "GRPC Client/Server framework"
documentation = "https://docs.rs/ntex-grpc"
repository = "https://github.com/ntex-rs/ntex-grpc"
readme = "README.md"
keywords = ["grpc"]
categories = ["asynchronous", "network-programming"]
edition = "2024"
rust-version = "1.95"

[lib]
name = "ntex_grpc"
path = "src/lib.rs"

[dependencies]
ntex-grpc-derive = { workspace = true }

ntex-error = { workspace = true }
ntex-h2 = { workspace = true }
ntex-http = { workspace = true }
ntex-io = { workspace = true }
ntex-net = { workspace = true }
ntex-util = { workspace = true }
ntex-bytes = { workspace = true }
ntex-service = { workspace = true }

bitflags = { workspace = true }
log = { workspace = true }
pin-project-lite = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
ntex = { workspace = true , features = ["openssl", "neon"] }
env_logger = { workspace = true }
openssl = { workspace = true }
