[workspace]
members = [
  "ntex-grpc",
  "ntex-grpc-codegen",
  "ntex-grpc-derive",
  "prost-build",
  "examples/custom",
  "examples/helloworld"
]
resolver = "3"

[patch.crates-io]
ntex-grpc = { path = "./ntex-grpc" }
ntex-grpc-derive = { path = "./ntex-grpc-derive" }
ntex-prost-build = { path = "./prost-build" }

[workspace.dependencies]
ntex-grpc = "3.3.0"
ntex-grpc-derive = "3.1.0"
ntex-grpc-codegen = "0.4.0"
ntex-prost-build = "0.14.0"

ntex = "4.1.0"
ntex-bytes = "1.11"
ntex-error = "3.0"
ntex-http = "2.1"
ntex-h2 = "4.2.0"
ntex-io = "4.3.0"
ntex-net = "4.3.0"
ntex-rt = "4.1.0"
ntex-util = "4.3.0"
ntex-service = "5.2.0"

base64 = "0.22"
flate2 = "1.1.3"
bitflags = "2"
clap = { version = "4.6", features = ["derive"] }
env_logger = "0.11"
heck = "0.5"
itertools = "0.15"
log = "0.4"
multimap = "0.10"
num_cpus = "1"
openssl = "0.10"
regex = "1.13"
pin-project-lite = "0.2"
proc-macro2 = "1"
quote = "1"
syn = "3"
tempfile = "3"
thiserror = "2"
urly = "1.1"
uuid = "1"
zstd = "0.13"
