[package]
name = "helloworld"
version = "3.0.0"
edition = "2024"
rust-version = "1.95"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
ntex = { workspace = true }
ntex-grpc = { workspace = true }
ntex-h2 = { workspace = true }

clap = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
num_cpus = { workspace = true }
