[package]
name = "ntex-prost-build"
version = "0.13.0"
authors = [
    "Dan Burkert <dan@danburkert.com>",
    "Tokio Contributors <team@tokio.rs>",
]
license = "Apache-2.0"
repository = "https://github.com/ntex-rs/ntex-grpc"
documentation = "https://docs.rs/ntex-prost-build"
readme = "README.md"
description = "A Protocol Buffers implementation for the Rust Language."
edition = "2021"

[features]
default = []
vendored = []

[dependencies]
log = { workspace = true }
heck = { workspace = true }
itertools = { workspace = true }
multimap = { workspace = true }
tempfile = { workspace = true }
regex = { workspace = true, default-features = false, features = ["std", "unicode-bool"] }

prost = { version = "0.14", default-features = false }
prost-types = { version = "0.14", default-features = false }

[build-dependencies]
which = "8"
cfg-if = "1"
cmake = "0.1"

[dev-dependencies]
env_logger = { workspace = true }
