[package]
name = "custom"
version = "3.0.0"
edition = "2024"
rust-version = "1.95"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
ntex = { workspace = true }
ntex-h2 = { workspace = true }
ntex-grpc = { workspace = true }

env_logger = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
